services:
  discord-weather:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TZ=America/Toronto
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
